project: <your wandb project name>
base_url: <your wandb instance url>
evals:
  - eval_type: helm
    model_name: <your model name>
    source: helm
    helm_output_dir: <your helm output dir path>
    helm_suite_name: <your helm suite name>
    token_per_iteration: <tokens per iteration in billions>
    benchmarks:
      - name: mmlu
        metrics:
          - EM
      - name: boolq
        metrics:
          - EM
      - name: quac
        metrics:
          - F1
      - name: raft
        metrics:
          - EM
      - name: hellaswag
        metrics:
          - EM
      - ...