# Process config example for dataset

# global parameters
project_name: 'demo-process'
dataset_path: './data/test_data.json'  # path to your dataset directory or file
export_path: './output/test_data.jsonl'

np: 4  # number of subprocess to process your dataset
text_keys: 'content'

# process schedule
# a list of several process operators with their arguments
process:
  - language_id_score_filter:
      lang: 'ko'